const ADD_SELECTED_ELEMENT = "ADD_SELECTED_ELEMENT";
const REMOVE_SELECTED_ELEMENT = "REMOVE_SELECTED_ELEMENT";
const UPDATE_SELECTED_ELEMENT = "UPDATE_SELECTED_ELEMENT";

const actions = {
  ADD_SELECTED_ELEMENT,
  REMOVE_SELECTED_ELEMENT,
  UPDATE_SELECTED_ELEMENT
};

export default actions;
